close all; clear; %clear classes; %clc;


%Create ground link
Ground = SRD_get_Link_Ground();

index = 1;
Body = SRD_get_Link(...
    'Order', index, ...
    'Name', 'Body', ...
    'RelativeBase', zeros(3, 1), ...
    'RelativeFollower', [0.5, 0;
                         0,   0;
                         0,   0], ...
    'RelativeCoM', [0.5;0;0], ...
    'Mass', 10, ...
    'Inertia', diag([0.1*1/12*10*0.5, 1/12*10*0.5, 1/12*10*0.5]), ...
    'ToDisplay', true, ...
    'Color', 'r', ...
    'StlPath', []);

Joint_1 = SRD_get_Joint_FloatingBase_XZ_plane(...
    'Name', 'Joint_1', ...
    'ChildLink',  Body, ...
    'ParentLink', Ground, ...
    'ParentFollowerNumber', 1, ...
    'UsedGeneralizedCoordinates', [1, 2, 3], ...
    'UsedControlInputs', [], ...
    'DefaultJointOrientation', eye(3));


index = index + 1;
FrontThigh = SRD_get_Link(...
    'Order', index, ...
    'Name', 'FrontThigh', ...
    'RelativeBase', zeros(3, 1), ...
    'RelativeFollower', [0;0;-0.3], ...
    'RelativeCoM', [0;0;0.15], ...
    'Mass', 2, ...
    'Inertia', diag([1/12*10*0.3, 1/12*10*0.3, 0.1*1/12*10*0.3]), ...
    'ToDisplay', true, ...
    'Color', 'r', ...
    'StlPath', []);
Joint_2 = SRD_get_Joint_PivotY(...
    'Name', 'Joint_1', ...
    'ChildLink',  FrontThigh, ...
    'ParentLink', Body, ...
    'ParentFollowerNumber', 1, ...
    'UsedGeneralizedCoordinates', 4, ...
    'UsedControlInputs', 1, ...
    'DefaultJointOrientation', eye(3));

index = index + 1;
BackThigh = SRD_get_Link(...
    'Order', index, ...
    'Name', 'BackThigh', ...
    'RelativeBase', zeros(3, 1), ...
    'RelativeFollower', [0;0;-0.3], ...
    'RelativeCoM', [0;0;0.15], ...
    'Mass', 2, ...
    'Inertia', diag([1/12*10*0.3, 1/12*10*0.3, 0.1*1/12*10*0.3]), ...
    'ToDisplay', true, ...
    'Color', 'r', ...
    'StlPath', []);

Joint_3 = SRD_get_Joint_PivotY(...
    'Name', 'Joint_1', ...
    'ChildLink',  BackThigh, ...
    'ParentLink', Body, ...
    'ParentFollowerNumber', 2, ...
    'UsedGeneralizedCoordinates', 5, ...
    'UsedControlInputs', 2, ...
    'DefaultJointOrientation', eye(3));


index = index + 1;
FrontShin = SRD_get_Link(...
    'Order', index, ...
    'Name', 'FrontShin', ...
    'RelativeBase', zeros(3, 1), ...
    'RelativeFollower', [0;0;-0.3], ...
    'RelativeCoM', [0;0;0.15], ...
    'Mass', 2, ...
    'Inertia', diag([1/12*10*0.3, 1/12*10*0.3, 0.1*1/12*10*0.3]), ...
    'ToDisplay', true, ...
    'Color', 'r', ...
    'StlPath', []);
Joint_4 = SRD_get_Joint_PivotY(...
    'Name', 'Joint_1', ...
    'ChildLink',  FrontShin, ...
    'ParentLink', FrontThigh, ...
    'ParentFollowerNumber', 1, ...
    'UsedGeneralizedCoordinates', 6, ...
    'UsedControlInputs', 3, ...
    'DefaultJointOrientation', eye(3));

index = index + 1;
BackShin = SRD_get_Link(...
    'Order', index, ...
    'Name', 'BackShin', ...
    'RelativeBase', zeros(3, 1), ...
    'RelativeFollower', [0;0;-0.3], ...
    'RelativeCoM', [0;0;0.15], ...
    'Mass', 2, ...
    'Inertia', diag([1/12*10*0.3, 1/12*10*0.3, 0.1*1/12*10*0.3]), ...
    'ToDisplay', true, ...
    'Color', 'r', ...
    'StlPath', []);
Joint_5 = SRD_get_Joint_PivotY(...
    'Name', 'Joint_1', ...
    'ChildLink',  BackShin, ...
    'ParentLink', BackThigh, ...
    'ParentFollowerNumber', 1, ...
    'UsedGeneralizedCoordinates', 7, ...
    'UsedControlInputs', 4, ...
    'DefaultJointOrientation', eye(3));


LinkArray = [Ground; Body; FrontThigh; BackThigh; FrontShin; BackShin]; %Create array of links
SRD_save(LinkArray, 'LinkArray');

InitialPosition = [0; 0.5; 0; -pi/6; -pi/6; pi/3; pi/3]; %Define initial position of the robot
% InitialPosition = [0; 0.6; 0; 0; 0; 0; 0]; %Define initial position of the robot
% InitialPosition = [0; 0.6; pi/6; pi/6; -pi/6; -3*pi/6; 0]; %Define initial position of the robot
SRD_save(InitialPosition, 'InitialPosition');

Chain = SRD_Chain(LinkArray);
SRD_save(Chain, 'Chain');
%Chain.Update(InitialPosition)


SRD_SetupVisuals('AxisLimits', [-1; 1; -1; 1; -1; 1], ...
    'ViewAngle', [-37.5, 30], ...
    'ToDrawMeshes', false, ...
    'Animation_ToUseGrid', true, ...
    'Animation_ToUseGridMinor', true, ...
    'DrawRobot_Default_RobotColor', [0.6 0.3 0], ...
    'DrawRobot_Default_EdgeAlpha', 0.3, ...
    'DrawRobot_Default_FaceAlpha', 1, ...
    'DrawRobot_Default_LineWidth', 0.5, ...
    'DrawRobot_STL_FaceColor', [0.8 0.8 1.0], ...
    'DrawRobot_STL_EdgeColor', 'none', ...
    'DrawRobot_STL_FaceLighting', 'gouraud', ...
    'DrawRobot_STL_AmbientStrength', 0.15, ...
    'DrawRobot_STL_camlight', 'headlight', ...
    'DrawRobot_STL_material', 'metal', ... %shiny dull metal
    'ToDrawFrames', false, ...
    'DrawRobot_Frame_Scale', 0.2, ...
    'DrawRobot_Frame_LineWidth', 1);

DrawRobot_function = SRD_DrawRobot_get_function('DrawRobot_Type', 'Default', ... %'Default' or 'STL' or 'Custom'
    'DrawRobot_Custom_handle', [], ...
    'Function_Type', 'DrawGivenPosition', ... %'DrawGivenPosition' or 'DrawInitialPosition'  or 'DrawCurrentPosition'
    'Chain', Chain);

DrawRobot_function(InitialPosition, [])
SRD__make_default_scene('Default')
            
